version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    ignore:
      - dependency-name: 'eslint'
        versions: ['>=10']
      - dependency-name: '@eslint/*'
        versions: ['>=10']

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
